apiVersion: v1
kind: Pod
metadata:
  name: docker-pod
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-agent-docker:latest
  - name: docker
    image: docker:latest
    command: ["dockerd"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock